/*Question histoire géo*/
/* Chapitre1*/
INSERT INTO questions (chapter_id, question, options, correct_answer) VALUES
(101, 'Entre quelles années se déroule la Première Guerre mondiale ?', '["1914-1918", "1939-1945", "1918-1939", "1914-1939"]', '1914-1918'),
(101, 'Comment appelle-t-on les soldats français de la Première Guerre mondiale ?', '["Les Gouttes", "Les Poilus", "Les Bleus", "Les Grognards"]', 'Les Poilus'),
(101, 'En quelle année a lieu la célèbre bataille de Verdun ?', '["1914", "1915", "1916", "1918"]', '1916'),
(101, 'Quel empire orchestre le génocide des Arméniens en 1915 ?', '["L''Empire austro-hongrois", "L''Empire ottoman", "L''Empire russe", "L''Empire allemand"]', 'L''Empire ottoman'),
(101, 'Quel traité est signé le 28 juin 1919 et impose de lourdes sanctions à l''Allemagne ?', '["Le traité de Francfort", "Le traité de Versailles", "Le traité de Brest-Litovsk", "Les accords de Munich"]', 'Le traité de Versailles'),
(101, 'Comment qualifie-t-on une guerre qui mobilise toutes les ressources économiques, militaires et civiles ?', '["Une guerre éclair", "Une guerre civile", "Une guerre totale", "Une guerre froide"]', 'Une guerre totale'),
(101, 'Quel terme désigne l''ensemble des techniques de diffusion d''informations pour influencer le moral et l''opinion ?', '["La censure", "La propagande", "Le rationnement", "La mobilisation"]', 'La propagande'),
(101, 'Quel nom donne-t-on aux femmes qui remplacent les hommes dans les usines d''armement pendant la Grande Guerre ?', '["Les suffragettes", "Les marraines de guerre", "Les munitionnettes", "Les résistantes"]', 'Les munitionnettes'),
(101, 'Quelle année charnière est marquée par les mutineries et le retrait de la Russie du conflit ?', '["1914", "1916", "1917", "1918"]', '1917'),
(101, 'Quel événement économique mondial éclate en octobre 1929 ?', '["Le krach boursier de Wall Street", "La crise pétrolière", "L''hyperinflation allemande", "La faillite de la Banque de France"]', 'Le krach boursier de Wall Street'),
(101, 'Qu''est-ce qu''un régime totalitaire ?', '["Un régime démocratique libéral", "Un État qui cherche à tout contrôler et utilise la terreur", "Une monarchie parlementaire", "Un gouvernement provisoire"]', 'Un État qui cherche à tout contrôler et utilise la terreur'),
(101, 'Qui dirige l''URSS en instaurant un régime totalitaire fondé sur la terreur et la collectivisation ?', '["Lénine", "Staline", "Trotski", "Kkhrouchchev"]', 'Staline'),
(101, 'Comment appelle-t-on le système de camps de travail forcé en URSS ?', '["Le ghetto", "Le Goulag", "Le camp de concentration", "L''Anschluss"]', 'Le Goulag'),
(101, 'En quelle année Adolf Hitler arrive-t-il au pouvoir en Allemagne ?', '["1929", "1933", "1936", "1939"]', '1933'),
(101, 'Quel est le nom du parti dirigé par Adolf Hitler ?', '["Le parti communiste", "Le parti national-socialiste (nazi)", "Le parti fasciste", "Le parti républicain"]', 'Le parti national-socialiste (nazi)'),
(101, 'Que signifie le concept d''"espace vital" (Lebensraum) pour les nazis ?', '["L''expansion territoriale vers l''Est pour le peuple allemand", "La colonisation de l''Afrique", "La création de l''ONU", "Le développement économique de la mer du Nord"]', 'L''expansion territoriale vers l''Est pour le peuple allemand'),
(101, 'Comment appelle-t-on l''annexion de l''Autriche par l''Allemagne en 1938 ?', '["Le blitzkrieg", "L''Anschluss", "La collaboration", "La Shoah"]', 'L''Anschluss'),
(101, 'Quelle politique les démocraties (France, Royaume-Uni) adoptent-elles face aux exigences d''Hitler dans les années 1930 ?', '["Une intervention militaire immédiate", "Une politique de conciliation (apaisement)", "Un blocus maritime", "Une alliance avec l''URSS"]', 'Une politique de conciliation (apaisement)'),
(101, 'À quelle date exacte commence la Seconde Guerre mondiale par l''invasion de la Pologne ?', '["1er septembre 1939", "11 novembre 1918", "18 juin 1940", "8 mai 1945"]', '1er septembre 1939'),
(101, 'Quelle tactique militaire rapide l''Allemagne utilise-t-elle au début de la Seconde Guerre mondiale ?', '["La guerre de position", "La Blitzkrieg (guerre éclair)", "La guerre des tranchées", "La guérilla"]', 'La Blitzkrieg (guerre éclair)'),
(101, 'Quel maréchal signe l''armistice avec l''Allemagne en juin 1940 en France ?', '["Le général de Gaulle", "Le maréchal Foch", "Le maréchal Pétain", "Georges Clemenceau"]', 'Le maréchal Pétain'),
(101, 'Quel régime politique autoritaire et réactionnaire est instauré en France à partir de juillet 1940 ?', '["La IIIe République", "Le régime de Vichy", "La IVe République", "Le Front populaire"]', 'Le régime de Vichy'),
(101, 'Quel est le slogan officiel du régime de Vichy ?', '["Liberté, Égalité, Fraternité", "Travail, Famille, Patrie", "Paix, Pain, Terre", "Honneur et Patrie"]', 'Travail, Famille, Patrie'),
(101, 'Qui lance l''appel du 18 juin 1940 depuis Londres pour refuser la défaite ?', '["Jean Moulin", "Le maréchal Pétain", "Le général de Gaulle", "Winston Churchill"]', 'Le général de Gaulle'),
(101, 'Comment appelle-t-on les combattants clandestins de l''intérieur en France pendant l''Occupation ?', '["Les FFL", "Les Résistants", "Les Collaborateurs", "Les Poilus"]', 'Les Résistants'),
(101, 'Qui unifie les mouvements de résistance intérieure à travers la création du CNR en 1943 ?', '["Jean Moulin", "Charles de Gaulle", "Pierre Mendès France", "Léon Blum"]', 'Jean Moulin'),
(101, 'Que signifie le mot hébreu "Shoah" ?', '["Victoire", "Catastrophe", "Souffrance", "Libération"]', 'Catastrophe'),
(101, 'Combien de Juifs environ ont été exterminés par les nazis durant la Seconde Guerre mondiale ?', '["1 million", "3 millions", "6 millions", "10 millions"]', '6 millions'),
(101, 'Lors de quelle conférence en janvier 1942 la "Solution finale" est-elle planifiée ?', '["La conférence de Munich", "La conférence de Wannsee", "La conférence de San Francisco", "La conférence de Yalta"]', 'La conférence de Wannsee'),
(101, 'Quel est le nom du plus grand complexe de camps de concentration et d''extermination nazi ?', '["Dachau", "Treblinka", "Auschwitz-Birkenau", "Mauthausen"]', 'Auschwitz-Birkenau'),
(101, 'Quel gaz toxique était principalement utilisé dans les chambres à gaz des centres de mise à mort nazis ?', '["Le gaz moutarde", "Le Zyclon B", "Le chlore", "Le monoxyde de carbone pur"]', 'Le Zyclon B'),
(101, 'Comment appelle-t-on le génocide des Tsiganes commis par les nazis ?', '["La Shoah", "Le Porajmos", "L''Anschluss", "Le Goulag"]', 'Le Porajmos'),
(101, 'Quelle bataille décisive sur le front de l''Est marque le tournant de la guerre en 1942-1943 ?', '["La bataille de la Marne", "La bataille de Stalingrad", "La bataille de Koursk", "La bataille d''Angleterre"]', 'La bataille de Stalingrad'),
(101, 'À quelle date a lieu le débarquement allié en Normandie (Jour J) ?', '["6 juin 1944", "8 mai 1945", "15 août 1944", "11 novembre 1942"]', '6 juin 1944'),
(101, 'Quand est signée la capitulation sans conditions de l''Allemagne (fin de la guerre en Europe) ?', '["11 novembre 1918", "8 mai 1945", "2 septembre 1945", "6 août 1945"]', '8 mai 1945'),
(101, 'Quelles villes japonaises subissent les bombardements atomiques américains en août 1945 ?', '["Tokyo et Kyoto", "Hiroshima et Nagasaki", "Osaka et Kobe", "Nara et Hiroshima"]', 'Hiroshima et Nagasaki'),
(101, 'Quel tribunal international juge les principaux criminels de guerre nazis entre 1945 et 1946 ?', '["Le tribunal de Tokyo", "Le procès de Nuremberg", "La Cour pénale internationale", "Le tribunal de La Haye"]', 'Le procès de Nuremberg'),
(101, 'Quelle notion juridique nouvelle est créée lors de ce procès pour punir les crimes contre les civils ?', '["Le crime de lèse-majesté", "Le crime contre l''humanité", "Le crime de haute trahison", "Le délit d''initié"]', 'Le crime contre l''humanité'),
(101, 'Quelle organisation internationale est fondée en juin 1945 pour préserver la paix mondiale ?', '["La SDN (Société des Nations)", "L''ONU (Organisation des Nations Unies)", "L''OTAN", "L''Union Européenne"]', 'L''ONU (Organisation des Nations Unies)'),
(101, 'Quelles sont les deux nouvelles superpuissances qui dominent le monde en 1945 ?', '["La France et le Royaume-Uni", "Les États-Unis et l''URSS", "L''Allemagne et le Japon", "La Chine et l''Inde"]', 'Les États-Unis et l''URSS');